# Generated by Django 5.0.4 on 2024-12-18 15:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='educator',
            name='address',
        ),
        migrations.RemoveField(
            model_name='educator',
            name='birthday',
        ),
        migrations.RemoveField(
            model_name='educator',
            name='contact_info',
        ),
    ]
