# Generated by Django 5.0.4 on 2024-12-18 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0002_remove_educator_address_remove_educator_birthday_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='educator',
            name='address',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='educator',
            name='birthday',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='educator',
            name='contact_info',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
