# Generated by Django 5.0.4 on 2024-12-18 16:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0003_educator_address_educator_birthday_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='educator',
            name='address',
        ),
        migrations.RemoveField(
            model_name='educator',
            name='birthday',
        ),
        migrations.RemoveField(
            model_name='educator',
            name='contact_info',
        ),
    ]
