# Generated by Django 5.0.4 on 2024-12-18 16:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0004_remove_educator_address_remove_educator_birthday_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='therapist',
            name='address',
        ),
        migrations.RemoveField(
            model_name='therapist',
            name='bio',
        ),
        migrations.RemoveField(
            model_name='therapist',
            name='birthday',
        ),
        migrations.RemoveField(
            model_name='therapist',
            name='contact_info',
        ),
    ]
